services:
  gateway:
    ports:
      - "5004:5004"
    environment:
      #      - LOGGING_LEVEL_ROOT=DEBUG
      - >-
        JAVA_TOOL_OPTIONS=
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5004
  user-service:
    ports:
      - "5005:5005"
    environment:
      #      LOGGING_LEVEL_ROOT: DEBUG
      - >-
        JAVA_TOOL_OPTIONS=
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  user-service-sync:
    scale: 1
    ports:
      - "5006:5006"
    environment:
      #      LOGGING_LEVEL_ROOT: DEBUG
      - >-
        JAVA_TOOL_OPTIONS=
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
