services:

  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway_container
    ports:
      - "443:443"
    environment:
      - DATA_REDIS_HOST=redis
      - DATA_REDIS_PORT=6379
      - DATA_REDIS_DATABASE=0
      - OTEL_SERVICE_NAME=gateway
      - OTEL_RESOURCE_ATTRIBUTES=service.instance.id=user-gateway-1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm-grafana:4318
    secrets:
      - KEY_PASSWORD
      - KEYSTORE_PASSWORD
    volumes:
      - ./.certs/gateway:/etc/ssl/gateway:ro
      - ./.certs/ca:/etc/ssl/ca:ro
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
      user-service-sync:
        condition: service_healthy
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    entrypoint: [ "/bin/sh", "/scripts/entrypoint_redis_ssl.sh" ]
    volumes:
      - ./.certs/redis:/etc/ssl/redis
      - ./.certs/redis-healthcheck:/etc/ssl/redis-healthcheck
      - ./.certs/ca:/etc/ssl/ca
      - ./scripts/entrypoint_redis_ssl.sh:/scripts/entrypoint_redis_ssl.sh:ro
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --tls --cacert /etc/ssl/ca/ca.crt --cert /etc/ssl/redis-healthcheck/redis-healthcheck.crt --key /etc/ssl/redis-healthcheck/redis-healthcheck.key ping | grep -q PONG" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_db_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    entrypoint: [ "/bin/bash", "/scripts/entrypoint_postgres_ssl.sh" ]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.certs/ca:/var/lib/postgresql/ca
      - ./.certs/postgres-db:/var/lib/postgresql/certs
      - ./scripts/entrypoint_postgres_ssl.sh:/scripts/entrypoint_postgres_ssl.sh:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h /var/run/postgresql -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s
    networks:
      - app-network

  debezium:
    image: debezium-postgres:3.6.2.Final
    build:
      context: .
      dockerfile: images/debezium-postgres/Dockerfile
    container_name: debezium_container
    ports:
      - "8083:8083"
    environment:
      KAFKA_HEAP_OPTS: "-Xms2g -Xmx2g"
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'

      ADVERTISED_HOST_NAME: debezium
      ADVERTISED_PORT: 8083

      #      ENABLE_OTEL: "true"
      #      OTEL_SERVICE_NAME: debezium
      #      OTEL_TRACES_EXPORTER: otlp
      #      OTEL_METRICS_EXPORTER: none
      #      OTEL_PROPAGATORS: tracecontext
      #      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm-grafana:4318
      #      OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "false"
      #      OTEL_TRACES_SAMPLER: "always_on"

      CONNECT_SECURITY_PROTOCOL: SSL
      CONNECT_SSL_KEYSTORE_TYPE: PKCS12
      CONNECT_SSL_KEYSTORE_LOCATION: /etc/ssl/debezium/debezium.p12
      CONNECT_SSL_KEYSTORE_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEYSTORE_PASSWORD}'
      CONNECT_SSL_KEY_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEY_PASSWORD}'
      CONNECT_SSL_TRUSTSTORE_TYPE: PKCS12
      CONNECT_SSL_TRUSTSTORE_LOCATION: /etc/ssl/debezium/debezium-truststore.p12
      CONNECT_SSL_TRUSTSTORE_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEYSTORE_PASSWORD}'
      CONNECT_SSL_PROTOCOL: TLSv1.3
      CONNECT_SSL_ENABLED_PROTOCOLS: TLSv1.3
      CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: HTTPS

      CONNECT_PRODUCER_SECURITY_PROTOCOL: SSL
      CONNECT_PRODUCER_SSL_KEYSTORE_TYPE: PKCS12
      CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION: /etc/ssl/debezium/debezium.p12
      CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEYSTORE_PASSWORD}'
      CONNECT_PRODUCER_SSL_KEY_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEY_PASSWORD}'
      CONNECT_PRODUCER_SSL_TRUSTSTORE_TYPE: PKCS12
      CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: /etc/ssl/debezium/debezium-truststore.p12
      CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEYSTORE_PASSWORD}'
      CONNECT_PRODUCER_SSL_PROTOCOL: TLSv1.3
      CONNECT_PRODUCER_SSL_ENABLED_PROTOCOLS: TLSv1.3
      CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: HTTPS
      #CONNECT_PRODUCER_INTERCEPTOR_CLASSES: io.debezium.tracing.DebeziumTracingProducerInterceptor
      CONNECT_CONFIG_PROVIDERS: fileprovider
      CONNECT_CONFIG_PROVIDERS_FILEPROVIDER_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
      CONNECT_CONFIG_PROVIDERS_FILEPROVIDER_PARAM_ALLOWED_PATHS: /run/secrets
    depends_on:
      user-service:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./.certs/debezium:/etc/ssl/debezium:ro
      - ./.certs/ca:/etc/ssl/ca:ro
    secrets:
      - KAFKA_CREDENTIALS_PROPERTIES
      - DEBEZIUM_CREDENTIALS_PROPERTIES
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/connectors" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s
    networks:
      - app-network

  debezium-initializer:
    image: curlimages/curl:8.21.0
    container_name: debezium_container_initializer
    depends_on:
      debezium:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      USER_EVENTS_TOPIC: ${USER_EVENTS_TOPIC}
      FRIENDSHIP_EVENTS_TOPIC: ${FRIENDSHIP_EVENTS_TOPIC}
    volumes:
      - ./.certs/debezium:/etc/ssl/debezium:ro
      - ./.certs/ca:/etc/ssl/ca:ro
      - ./scripts/init_debezium.sh:/scripts/init_debezium.sh:ro
    secrets:
      - DEBEZIUM_CREDENTIALS_PROPERTIES
    entrypoint: [ "/bin/sh", "/scripts/init_debezium.sh" ]
    networks:
      - app-network

  mongo-db:
    image: mongo:8.2.12
    container_name: mongodb_container
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_DB_ROOT_PASSWORD
    secrets:
      - MONGO_DB_ROOT_PASSWORD
    entrypoint: [ "/bin/bash", "/scripts/entrypoint_mongo_ssl.sh" ]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./.certs/mongo-db:/etc/ssl/mongo-db
      - ./.certs/mongo-healthcheck:/etc/ssl/mongo-healthcheck
      - ./.certs/ca:/etc/ssl/ca
      - ./scripts/entrypoint_mongo_ssl.sh:/scripts/entrypoint_mongo_ssl.sh:ro
    healthcheck:
      test: >-
        mongosh
        --host localhost
        --port 27017
        --tls
        --tlsCAFile /etc/ssl/ca/ca.crt
        --tlsCertificateKeyFile /etc/ssl/mongo-healthcheck/mongo-healthcheck.pem
        --tlsAllowInvalidHostnames=false
        --quiet
        --eval 'if (db.runCommand("ping").ok !== 1) { quit(1); }'
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s
    networks:
      - app-network

  mongo-db-replica_initializer:
    image: mongo:8.2.12
    container_name: mongodb_container_replica_initializer
    restart: "no"
    depends_on:
      mongo-db:
        condition: service_healthy
    volumes:
      - ./.certs/ca:/etc/ssl/ca:ro
      - ./.certs/mongo-healthcheck:/etc/ssl/mongo-healthcheck:ro
      - ./scripts/init_mongo_replica.sh:/scripts/init_mongo_replica.sh:ro
    entrypoint: [ "/bin/bash", "/scripts/init_mongo_replica.sh" ]
    environment:
      MONGO_REPLICA_NAME: ${MONGO_REPLICA_NAME}
      MONGO_DB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
    secrets:
      - MONGO_DB_ROOT_PASSWORD
    networks:
      - app-network

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka_container
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CLIENT://:9092,INTERNAL://:9094,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092,INTERNAL://kafka:9094,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:SSL,INTERNAL:SSL,EXTERNAL:SSL,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_NETWORK_THREADS: 4
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_NUM_REPLICA_FETCHERS: 2
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 1048576
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 1048576
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600

      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/ssl/kafka/kafka.p12
      KAFKA_SSL_KEYSTORE_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEYSTORE_PASSWORD}'
      KAFKA_SSL_KEY_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEY_PASSWORD}'

      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/ssl/kafka/kafka-truststore.p12
      KAFKA_SSL_TRUSTSTORE_PASSWORD: '$${fileprovider:/run/secrets/KAFKA_CREDENTIALS_PROPERTIES:KEYSTORE_PASSWORD}'
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_PROTOCOL: TLSv1.3
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.3
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: HTTPS
      KAFKA_CONFIG_PROVIDERS: fileprovider
      KAFKA_CONFIG_PROVIDERS_FILEPROVIDER_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
      KAFKA_CONFIG_PROVIDERS_FILEPROVIDER_PARAM_ALLOWED_PATHS: /run/secrets
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./.certs/kafka:/etc/ssl/kafka:ro
      - ./.certs/kafka-healthcheck:/etc/ssl/kafka-healthcheck:ro
      - ./.certs/ca:/etc/ssl/ca:ro
    secrets:
      - KAFKA_CREDENTIALS_PROPERTIES
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list \
          --command-config /etc/ssl/kafka-healthcheck/client.properties "
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s
    networks:
      - app-network

  kafka-topic-initializer:
    image: apache/kafka:3.7.2
    container_name: kafka_topic_initializer_container
    restart: "no"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_LISTENER_CONCURRENCY: 6
      USER_EVENTS_TOPIC: ${USER_EVENTS_TOPIC}
      FRIENDSHIP_EVENTS_TOPIC: ${FRIENDSHIP_EVENTS_TOPIC}
      USER_EVENTS_RESPONSE_TOPIC: ${USER_EVENTS_RESPONSE_TOPIC}
      FRIENDSHIP_EVENTS_RESPONSE_TOPIC: ${FRIENDSHIP_EVENTS_RESPONSE_TOPIC}
    volumes:
      - ./.certs/kafka:/etc/ssl/kafka:ro
      - ./.certs/kafka-healthcheck:/etc/ssl/kafka-healthcheck:ro
      - ./.certs/ca:/etc/ssl/ca:ro
      - ./scripts/init_kafka_topics.sh:/scripts/init_kafka_topics.sh:ro
    entrypoint: [ "/bin/sh", "/scripts/init_kafka_topics.sh" ]
    networks:
      - app-network

  user-service:
    image: user-service:latest
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user_service_container
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - USER_EVENTS_TOPIC=${USER_EVENTS_TOPIC}
      - FRIENDSHIP_EVENTS_TOPIC=${FRIENDSHIP_EVENTS_TOPIC}
      - USER_EVENTS_RESPONSE_TOPIC=${USER_EVENTS_RESPONSE_TOPIC}
      - FRIENDSHIP_EVENTS_RESPONSE_TOPIC=${FRIENDSHIP_EVENTS_RESPONSE_TOPIC}
      - OTEL_SERVICE_NAME=user-service
      - OTEL_RESOURCE_ATTRIBUTES=service.instance.id=user-service-1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm-grafana:4318
      - REDIS_HOST=redis
      - KAFKA_LISTENER_CONCURRENCY=3
    secrets:
      - POSTGRES_PASSWORD
      - KEY_PASSWORD
      - KEYSTORE_PASSWORD
    volumes:
      - ./.certs/user-service:/etc/ssl/user-service:ro
      - ./.certs/ca:/etc/ssl/ca:ro
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health/liveness > /dev/null || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-topic-initializer:
        condition: service_completed_successfully
    networks:
      - app-network

  user-service-sync:
    image: user-service-sync:latest
    build:
      context: .
      dockerfile: user-service-sync/Dockerfile
    scale: 2
    ports:
      - "8081"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=user-events-consumer
      - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
      - MONGO_DB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - USER_EVENTS_TOPIC=${USER_EVENTS_TOPIC}
      - FRIENDSHIP_EVENTS_TOPIC=${FRIENDSHIP_EVENTS_TOPIC}
      - USER_EVENTS_RESPONSE_TOPIC=${USER_EVENTS_RESPONSE_TOPIC}
      - FRIENDSHIP_EVENTS_RESPONSE_TOPIC=${FRIENDSHIP_EVENTS_RESPONSE_TOPIC}
      - REDIS_HOST=redis
      - MONGO_REPLICA_NAME=${MONGO_REPLICA_NAME}
      - OTEL_SERVICE_NAME=user-service-sync
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm-grafana:4318
      - KAFKA_LISTENER_CONCURRENCY=3
    secrets:
      - MONGO_DB_ROOT_PASSWORD
      - KEY_PASSWORD
      - KEYSTORE_PASSWORD
    volumes:
      - ./.certs/user-service-sync:/etc/ssl/user-service-sync:ro
      - ./.certs/ca:/etc/ssl/ca:ro
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8081/actuator/health/liveness > /dev/null || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s
    depends_on:
      kafka:
        condition: service_healthy
      kafka-topic-initializer:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      mongo-db-replica_initializer:
        condition: service_completed_successfully
    networks:
      - app-network

  lgtm-grafana:
    image: grafana/otel-lgtm:0.24.0
    container_name: lgtm_container
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - lgtm_data:/data
      - "./grafana/RED Metrics (my histogram).json:/otel-lgtm/grafana-dashboard-red-metrics-native.json:ro"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  kafka_data:
    driver: local
  lgtm_data:
    driver: local

secrets:
  POSTGRES_PASSWORD:
    file: ./.secrets/POSTGRES_PASSWORD
  MONGO_DB_ROOT_PASSWORD:
    file: ./.secrets/MONGO_DB_ROOT_PASSWORD
  KEY_PASSWORD:
    file: ./.secrets/KEY_PASSWORD
  KEYSTORE_PASSWORD:
    file: ./.secrets/KEYSTORE_PASSWORD
  KAFKA_CREDENTIALS_PROPERTIES:
    file: ./.secrets/kafka-credentials.properties
  DEBEZIUM_CREDENTIALS_PROPERTIES:
    file: ./.secrets/debezium-credentials.properties
