server.port=443
server.ssl.bundle=app
spring.data.redis.host=${DATA_REDIS_HOST:localhost}
spring.data.redis.port=${DATA_REDIS_PORT:6379}
spring.data.redis.ssl.enabled=true
spring.data.redis.ssl.bundle=app

spring.ssl.bundle.jks.app.key.alias=gateway
spring.ssl.bundle.jks.app.key.password=${KEY_PASSWORD}
spring.ssl.bundle.jks.app.keystore.location=file:${GATEWAY_KEYSTORE_LOCATION}
spring.ssl.bundle.jks.app.keystore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.keystore.type=PKCS12
spring.ssl.bundle.jks.app.truststore.location=file:${CA_TRUSTSTORE_LOCATION}
spring.ssl.bundle.jks.app.truststore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.truststore.type=PKCS12
