spring.application.name=gateway
server.port=443
server.ssl.bundle=app

spring.data.redis.host=${DATA_REDIS_HOST:localhost}
spring.data.redis.port=${DATA_REDIS_PORT:6379}
spring.data.redis.ssl.enabled=true
spring.data.redis.ssl.bundle=app

spring.ssl.bundle.jks.app.key.alias=gateway
spring.ssl.bundle.jks.app.key.password=${KEY_PASSWORD}
spring.ssl.bundle.jks.app.keystore.location=file:/etc/ssl/gateway/gateway.p12
spring.ssl.bundle.jks.app.keystore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.keystore.type=PKCS12
spring.ssl.bundle.jks.app.truststore.location=file:/etc/ssl/ca/ca-truststore.p12
spring.ssl.bundle.jks.app.truststore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.truststore.type=PKCS12


spring.cloud.gateway.server.webflux.trusted-proxies=

spring.cloud.gateway.server.webflux.x-forwarded.enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.for-enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.host-enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.port-enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.proto-enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.prefix-enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.for-append=true
spring.cloud.gateway.server.webflux.x-forwarded.host-append=true
spring.cloud.gateway.server.webflux.x-forwarded.port-append=true
spring.cloud.gateway.server.webflux.x-forwarded.proto-append=true
spring.cloud.gateway.server.webflux.x-forwarded.prefix-append=true
spring.cloud.gateway.server.webflux.forwarded.enabled=true
spring.cloud.gateway.server.webflux.forwarded.by.enabled=true

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.core.codec=TRACE
logging.level.org.springframework.http.codec=TRACE
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/main/v3/api-docs

springdoc.swagger-ui.urls[1].name=User Sync Service
springdoc.swagger-ui.urls[1].url=/replica/v3/api-docs

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
management.opentelemetry.enabled=true
management.tracing.sampling.probability=1.0
management.metrics.distribution.slo.http.server.requests=10ms,25ms,50ms,100ms,250ms,500ms,1s,2s

management.logging.export.otlp.enabled=true
management.tracing.export.otlp.enabled=true
management.otlp.metrics.export.step=10s
management.otlp.metrics.export.enabled=true
management.observations.annotations.enabled=true
management.observations.enable.spring.security=false
spring.task.execution.propagate-context=true

spring.config.import=classpath:users-gateway.properties,classpath:users-sync-gateway.properties,optional:configtree:/run/secrets/
