gateway.routes.replica.id=user-service-sync1
gateway.routes.replica.hosts=localhost,friends
gateway.routes.replica.destination=http://user-service-sync1:8081

gateway.routes.replica.rate-limit.replenish-rate=2
gateway.routes.replica.rate-limit.burst-capacity=20
gateway.routes.replica.rate-limit.requested-tokens=1

resilience4j.circuitbreaker.instances.replica.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.replica.slidingWindowSize=10
resilience4j.circuitbreaker.instances.replica.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.replica.failureRateThreshold=50
resilience4j.circuitbreaker.instances.replica.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.replica.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.replica.automaticTransitionFromOpenToHalfOpenEnabled=true