gateway.routes.replica.id=user-service-sync
gateway.routes.replica.hosts=localhost,friends
gateway.routes.replica.destination=http://user-service-sync:8081

# For Gatling tests, these values are set for high throughput
gateway.routes.replica.rate-limit.replenish-rate=500
gateway.routes.replica.rate-limit.burst-capacity=500
gateway.routes.replica.rate-limit.requested-tokens=1

resilience4j.circuitbreaker.instances.replica.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.replica.slidingWindowSize=10
resilience4j.circuitbreaker.instances.replica.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.replica.failureRateThreshold=50
resilience4j.circuitbreaker.instances.replica.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.replica.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.replica.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.timelimiter.instances.replica.timeoutDuration=5s
resilience4j.timelimiter.instances.replica.cancelRunningFuture=true