gateway.routes.main.id=user-service
gateway.routes.main.hosts=localhost,friends
gateway.routes.main.destination=http://user-service:8080

# For Gatling tests, these values are set for high throughput.
gateway.routes.main.rate-limit.replenish-rate=500
gateway.routes.main.rate-limit.burst-capacity=500
gateway.routes.main.rate-limit.requested-tokens=1

resilience4j.circuitbreaker.instances.main.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.main.slidingWindowSize=10
resilience4j.circuitbreaker.instances.main.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.main.failureRateThreshold=50
resilience4j.circuitbreaker.instances.main.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.main.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.main.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.timelimiter.instances.main.timeoutDuration=5s
resilience4j.timelimiter.instances.main.cancelRunningFuture=true