{
 "title": "My Metric",
 "description": "request rate, error rate, duration",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Log W/E Level Rate (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name, service_instance_id)(\n  rate(\n    {service_name=~\"$job\", service_instance_id=~\"$instance\"}\n    | severity_text=\"WARN\"\n    [2m]\n  )\n)",
     "legendFormat": "WARN {{service_name}} / {{service_instance_id}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name, service_instance_id)(\n  rate(\n    {service_name=~\"$job\", service_instance_id=~\"$instance\"}\n    | severity_text=\"ERROR\"\n    [5m]\n  )\n)",
     "legendFormat": "ERROR {{service_name}} / {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Avg Trace Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"user-service\" && span:kind=server && span.my.tag=\"user-new\"} | avg_over_time(trace:duration) by (span.my.tag)",
     "tableType": "traces"
    },
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"user-service\" && span:kind=server && span.my.tag=\"friendship-add-new\"} | avg_over_time(trace:duration) by (span.my.tag)",
     "tableType": "traces"
    },
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"user-service-sync\" && span:kind=server && span.my.tag=\"replica-friendships-all\"} | avg_over_time(trace:duration) by (span.my.tag)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Request Rate (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (rate(http_server_requests_milliseconds_count{job=~\"$job\", instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{job}} / {{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 * sum(\n  rate(\n    http_server_requests_milliseconds_count{\n      status=~\"5..\"\n    }[2m]\n  )\n)\n/\nsum(\n  rate(\n    http_server_requests_milliseconds_count[2m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration histogram (s)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    http_server_requests_milliseconds_bucket{\n      job=~\"$job\",\n      instance=~\"$instance\"\n    }[2m]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration Heatmap (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    http_server_requests_milliseconds_bucket{\n      job=~\"$job\",\n      instance=~\"$instance\"\n    }[2m]\n  )\n)"
    }
   ]
  }
 ]
}