server.port=8081
server.forward-headers-strategy=framework

spring.application.name=user-service-sync
spring.jackson.time-zone=UTC
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
spring.threads.virtual.enabled=true

springdoc.cache.disabled=true

spring.config.import=optional:configtree:/run/secrets/

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=true
spring.data.redis.ssl.bundle=app

spring.ssl.bundle.jks.app.key.alias=user-service-sync
spring.ssl.bundle.jks.app.key.password=${KEY_PASSWORD}
spring.ssl.bundle.jks.app.keystore.location=file:/etc/ssl/user-service-sync/user-service-sync.p12
spring.ssl.bundle.jks.app.keystore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.keystore.type=PKCS12
spring.ssl.bundle.jks.app.truststore.location=file:/etc/ssl/ca/ca-truststore.p12
spring.ssl.bundle.jks.app.truststore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.truststore.type=PKCS12

spring.cache.type=redis
spring.cache.redis.time-to-live=20s
spring.cache.redis.cache-null-values=false
spring.cache.redis.key-prefix=user-service-sync::

spring.mongodb.representation.uuid=standard
spring.mongodb.uri=mongodb://${MONGO_DB_ROOT_USERNAME}:${MONGO_DB_ROOT_PASSWORD}@mongo-db:27017/${MONGO_DB_DATABASE}?authSource=admin
spring.mongodb.ssl.enabled=true
spring.mongodb.ssl.bundle=app
spring.mongodb.replica-set-name=${MONGO_REPLICA_NAME}
spring.data.mongodb.ssl.invalid-hostname-allowed=false

flamingock.enabled=true
flamingock.management-mode=application_runner

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.apache.kafka.common.network=DEBUG
#logging.level.org.apache.kafka.common.security.ssl=DEBUG
#logging.level.org.springframework.kafka=DEBUG
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.reconnect.backoff.max.ms=10000
spring.kafka.listener.concurrency=${KAFKA_LISTENER_CONCURRENCY}
spring.kafka.listener.ack-mode=record
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:user-events-consumer}
spring.kafka.security.protocol=SSL
spring.kafka.ssl.key-store-location=file:/etc/ssl/user-service-sync/user-service-sync.p12
spring.kafka.ssl.key-store-password=${KEYSTORE_PASSWORD}
spring.kafka.ssl.key-password=${KEY_PASSWORD}
spring.kafka.ssl.key-store-type=PKCS12
spring.kafka.ssl.trust-store-location=file:/etc/ssl/ca/ca-truststore.p12
spring.kafka.ssl.trust-store-password=${KEYSTORE_PASSWORD}
spring.kafka.ssl.trust-store-type=PKCS12
spring.kafka.ssl.protocol=TLSv1.3
spring.kafka.ssl.enabled-protocols=TLSv1.3
spring.kafka.ssl.endpoint-identification-algorithm=HTTPS

spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.max-poll-records=1000
spring.kafka.consumer.max-poll-interval=2700000
spring.kafka.consumer.properties.fetch.max.wait.ms=10
spring.kafka.consumer.properties.fetch.min.bytes=1
spring.kafka.consumer.properties.fetch.max.bytes=52428800
spring.kafka.consumer.properties.max.partition.fetch.bytes=4194304
spring.kafka.consumer.properties.partition.assignment.strategy=org.apache.kafka.clients.consumer.CooperativeStickyAssignor
spring.kafka.listener.observation-enabled=true

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
spring.kafka.template.observation-enabled=true

app.events.user-events-topic=${USER_EVENTS_TOPIC:user-events}
app.events.friendship-events-topic=${FRIENDSHIP_EVENTS_TOPIC:friendship-events}
app.events.response.user-events-topic=${USER_EVENTS_RESPONSE_TOPIC:user-events-response}
app.events.response.friendship-events-topic=${FRIENDSHIP_EVENTS_RESPONSE_TOPIC:friendship-events-response}

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
management.opentelemetry.enabled=true
management.opentelemetry.resource-attributes.[service.instance.id]=user-service-sync-${HOSTNAME}
management.tracing.sampling.probability=1.0
management.metrics.distribution.slo.http.server.requests=10ms,25ms,50ms,100ms,250ms,500ms,1s,2s

management.logging.export.otlp.enabled=true
management.tracing.export.otlp.enabled=true
management.tracing.enabled=true
management.otlp.metrics.export.step=10s
management.otlp.metrics.export.enabled=true
management.metrics.mongodb.command.enabled=false
management.metrics.mongodb.connectionpool.enabled=false
management.observations.annotations.enabled=true
management.observations.enable.spring.security=false
spring.task.execution.propagate-context=true

#logging.level.io.opentelemetry=DEBUG
#logging.level.io.opentelemetry.sdk=DEBUG
#logging.level.io.opentelemetry.instrumentation=DEBUG
