spring.config.import=optional:configtree:/run/secrets/

spring.data.redis.ssl.enabled=true
spring.data.redis.ssl.bundle=app

spring.ssl.bundle.jks.app.key.alias=user-service-sync
spring.ssl.bundle.jks.app.key.password=${KEY_PASSWORD}
spring.ssl.bundle.jks.app.keystore.location=file:${USER_SERVICE_SYNC_KEYSTORE_LOCATION}
spring.ssl.bundle.jks.app.keystore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.keystore.type=PKCS12
spring.ssl.bundle.jks.app.truststore.location=file:${CA_TRUSTSTORE_LOCATION}
spring.ssl.bundle.jks.app.truststore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.truststore.type=PKCS12

spring.mongodb.ssl.enabled=true
spring.mongodb.ssl.bundle=app
spring.data.mongodb.ssl.invalid-hostname-allowed=false

spring.kafka.security.protocol=SSL
spring.kafka.ssl.key-store-location=file:${USER_SERVICE_SYNC_KEYSTORE_LOCATION}
spring.kafka.ssl.key-store-password=${KEYSTORE_PASSWORD}
spring.kafka.ssl.key-password=${KEY_PASSWORD}
spring.kafka.ssl.key-store-type=PKCS12
spring.kafka.ssl.trust-store-location=file:${CA_TRUSTSTORE_LOCATION}
spring.kafka.ssl.trust-store-password=${KEYSTORE_PASSWORD}
spring.kafka.ssl.trust-store-type=PKCS12
spring.kafka.ssl.protocol=TLSv1.3
spring.kafka.ssl.enabled-protocols=TLSv1.3
spring.kafka.ssl.endpoint-identification-algorithm=HTTPS



