spring.config.import=optional:configtree:/run/secrets/
ssl.key=${KEY_PASSWORD}

spring.data.redis.ssl.enabled=true
spring.data.redis.ssl.bundle=app

spring.ssl.bundle.jks.app.key.alias=user-service
spring.ssl.bundle.jks.app.key.password=${KEY_PASSWORD}
spring.ssl.bundle.jks.app.keystore.location=file:${USER_SERVICE_KEYSTORE_LOCATION}
spring.ssl.bundle.jks.app.keystore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.keystore.type=PKCS12
spring.ssl.bundle.jks.app.truststore.location=file:${CA_TRUSTSTORE_LOCATION}
spring.ssl.bundle.jks.app.truststore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.app.truststore.type=PKCS12

spring.flyway.jdbc-properties.ssl=true
spring.flyway.jdbc-properties.sslmode=verify-full
spring.flyway.jdbc-properties.sslcert=${USER_SERVICE_CERT_LOCATION}
spring.flyway.jdbc-properties.sslkey=${USER_SERVICE_KEY_LOCATION}
spring.flyway.jdbc-properties.sslrootcert=${CA_CERT_LOCATION}
spring.flyway.jdbc-properties.sslpassword=${ssl.key}

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=verify-full
spring.datasource.hikari.data-source-properties.sslcert=${USER_SERVICE_CERT_LOCATION}
spring.datasource.hikari.data-source-properties.sslkey=${USER_SERVICE_KEY_LOCATION}
spring.datasource.hikari.data-source-properties.sslrootcert=${CA_CERT_LOCATION}
spring.datasource.hikari.data-source-properties.sslpassword=${ssl.key}

spring.kafka.security.protocol=SSL
spring.kafka.ssl.key-store-location=file:${USER_SERVICE_KEYSTORE_LOCATION}
spring.kafka.ssl.key-store-password=${KEYSTORE_PASSWORD}
spring.kafka.ssl.key-password=${KEY_PASSWORD}
spring.kafka.ssl.key-store-type=PKCS12
spring.kafka.ssl.trust-store-location=file:${CA_TRUSTSTORE_LOCATION}
spring.kafka.ssl.trust-store-password=${KEYSTORE_PASSWORD}
spring.kafka.ssl.trust-store-type=PKCS12
spring.kafka.ssl.protocol=TLSv1.3
spring.kafka.ssl.enabled-protocols=TLSv1.3
spring.kafka.ssl.endpoint-identification-algorithm=HTTPS
